---
- name: Check distribution and version
  debug:
    var: ansible_distribution_major_version

- name: Install python-x packages based on distribution version
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes 
    cache_valid_time: 3600
  loop: "{{ python2_packages }}"
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 21 ) or(ansible_distribution == 'Debian' and ansible_distribution_major_version|int < 11 )

- name: Install python3-x packages based on distribution version
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes 
    cache_valid_time: 3600
  loop: "{{ python3_packages }}"
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 20 ) or (ansible_distribution == 'Debian' and ansible_distribution_major_version|int > 10 )

- name: Install any necessary dependencies [Debian/Ubuntu]
  apt: 
    name:
      - curl
      - apt-transport-https
    state: present 
    update_cache: yes 
    cache_valid_time: 3600
    
- name: Install any necessary PIP dependencies [Debian/Ubuntu]
  apt: 
    name: python-pip
    state: present 
    update_cache: yes
    cache_valid_time: 3600
  when: influxdb_install_python_client

- name: Import InfluxData GPG signing key [Debian/Ubuntu]
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Add InfluxData repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ influxdb_install_version }}
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB packages [Debian/Ubuntu]
  apt: 
    name: "{{ influxdb_package_name }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: influxdb_install_url is not defined or influxdb_install_url == None
  
- name: Download InfluxDB package via URL [Debian/Ubuntu]
  command: curl -o /tmp/influxdb-ansible-download.deb {{ influxdb_install_url }}
  when: influxdb_install_url is defined and influxdb_install_url != None

- name: Install downloaded InfluxDB package [Debian/Ubuntu]
  apt:
    deb: /tmp/influxdb-ansible-download.deb
    state: present
  when: influxdb_install_url is defined and influxdb_install_url != None
